### ISSUE TITLE
How to run on Android ? 

### ISSUE THREAD

**Issue by ingnelson** [vproxy666/v-proxy#1]
Hello sir . 
is there a way to run it on android ?

what app should i use ?

how to change the port 443 for other port ?

**Comment by vproxy666** [comment]
> is there a way to run it on android ?

V-Proxy is a server-side application.  

> what app should i use ?

At this moment, only iOS and Firefox are supported.
Proxydroid will adapte with v-proxy on Android as a client, but not ready yet.

> how to change the port 443 for other port ?

Via `https_port` parameter on startup, example goes below.

```
sudo docker run -d \
     --name vproxy \
     --network host \
     --restart=always \
     -v vproxy-data:/app/data/:rw \
     -v vproxy-data:/etc/letsencrypt:rw \
     -v vproxy-data:/var/lib/letsencrypt:rw \
     --cap-add net_bind_service \
     vproxy/server:v0.2.8 --https_port=11443
```
